{{- $platform := "bmrg" -}}
{{- $product := "bosun" -}}
{{- $tier := "certs" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bmrg.name" (dict "context" $ "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $ "tier" $tier ) | nindent 4 }}
type: Opaque
data:
  boomerang.crt: {{ $.Values.certs.boomerang }}
