apiVersion: v2
name: bmrg-flow
description: Boomerang Flow
type: application
version: 5.4.3
appVersion: 4.0.0
home: https://useboomerang.io
dependencies:
  - name: bmrg-common
    repository: https://raw.githubusercontent.com/boomerang-io/charts/index
    version: 3.0.2
    alias: ch
  - name: oauth2-proxy
    version: 6.17.1
    repository: https://oauth2-proxy.github.io/manifests
    alias: oauth2proxy
    condition: oauth2proxy.enabled
keywords:
  - boomerang
  - flow
  - workflows
  - oauth2-proxy
