apiVersion: v2
name: bmrg-flow
description: Boomerang Flow
type: application
version: 4.5.1
appVersion: 3.1.0
home: https://useboomerang.io
dependencies:
  - name: bmrg-common
    repository: https://raw.githubusercontent.com/boomerang-io/charts/index
    version: ~2.0.3
    alias: ch
keywords:
- boomerang
- flow