# This is a YAML-formatted file.
# Declare variables, and default values, to be passed into your templates.

#General Configuration
general:
  namePrefix: bmrg-bosun
  enable:
    apidocs: false
    debug: false
    standalone: true

#Boomerang Integrations
#Needed if general.enable.standalone=false
core:
  namePrefix: bmrg-core
  namespace: #needed if installed in different namespace
  ingressRoot:
boomerang:
  cicd:
    namePrefix: bmrg-cicd
    namespace: #needed if installed in different namespace

# General Image Configuration
image:
  registry: boomerangio
  pullPolicy: IfNotPresent
  pullSecret:

# Job Configuraiton
job:
  data:
    enabled: true
    profile: bosun
    image:
      repository: /bosun-loader
      tag: 0.1.1

# Web App Configuration
apps:
  bosun:
    image:
      repository: /bosun-client-web
      tag: 0.3.0
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted

# Micro Service Configuration
# Note: There are if conditions in the template referencing the service name i.e. urbancode
services:
  policy:
    image:
      repository: /bosun-service-policy
      tag: 2.5.4
    replicaCount: 1
    service:
      type: ClusterIP
    zone: untrusted
  repository:
    image:
      repository: /bosun-service-repository
      tag: 0.1.3
    replicaCount: 1
    service:
      type: ClusterIP
    zone: semi-trusted

opa:
  image:
    repository: openpolicyagent/opa
    tag: 0.13.5
  replicaCount: 1
  service:
    type: ClusterIP
  zone: trusted

# Global configuration. This can be overriden by a parent chart.
global:
  database:
    mongodb:
      host: bmrg-mdb001-ibm-mongodb-dev
      port: 27017
      database: boomerang
      args:
      user: boomerang
      password: passw0rd
      secretName:
      tlsSecretName:
  ingress:
    enabled: false
    root: /bosun
    host: host.example.io
    tlsSecretName: bmrg-tls-cloud
    # The prefix for the annotations inside the ingress definition. Typically for IKS Community Ingress
    # you need to set it to "nginx.global.ingress.kubernetes.io"
    annotationsPrefix: "ingress.kubernetes.io"
    # The class of the ingress, it is used to mark the ingress resources to be picked-up by a specific
    # controller. For IKS Community Ingress set it to "public-iks-k8s-nginx"
    class: "nginx"
    pathType: ImplementationSpecific
  auth:
    enabled: false
    mode: basic
    serviceName: bmrg-auth-proxy
    namespace: bmrg-core
    prefix: /oauth
    tokenURL: http://bmrg-core-services-auth.bmrg-core.svc.cluster.local/auth/token/validate/external
    signOutRedirect:

hostAliases: []

proxy:
  enable: false
  host:
  port:
  ignore:

monitoring:
  instana:
    enable: false
    browser:
      reportingUrl:
      key:
  newrelic:
    enable: false
    apm:
      name: Boomerang Private
      key:
      image:
        registry: boomerangio
        repository: /util-newrelicjavaagent
        tag: 5.14.0
    browser:
      id:
      key:

# Integration to XRay. Only needed in Standalone mode.
xray:
  token:
  url:
  user:

# Integration to Sonarqube. Only needed in Standalone mode.
sonarqube:
  token:
  url:

certs:
  boomerang: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUhUakNDQmphZ0F3SUJBZ0lRQVpONDdRYUxVUEp4N3Q3ZEZhTzhWVEFOQmdrcWhraUc5dzBCQVFzRkFEQkUKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVI0d0hBWURWUVFERXhWSApaVzlVY25WemRDQkZWaUJTVTBFZ1EwRWdSekl3SGhjTk1qVXdNekF6TURBd01EQXdXaGNOTWpZd016QTBNak0xCk9UVTVXakNCNWpFVE1CRUdDeXNHQVFRQmdqYzhBZ0VERXdKVlV6RVpNQmNHQ3lzR0FRUUJnamM4QWdFQ0V3aE8KWlhjZ1dXOXlhekVkTUJzR0ExVUVEd3dVVUhKcGRtRjBaU0JQY21kaGJtbDZZWFJwYjI0eERqQU1CZ05WQkFVVApCVE13TURVNU1Rc3dDUVlEVlFRR0V3SlZVekVSTUE4R0ExVUVDQk1JVG1WM0lGbHZjbXN4RHpBTkJnTlZCQWNUCkJrRnliVzl1YXpFME1ESUdBMVVFQ2hNclNXNTBaWEp1WVhScGIyNWhiQ0JDZFhOcGJtVnpjeUJOWVdOb2FXNWwKY3lCRGIzSndiM0poZEdsdmJqRWVNQndHQTFVRUF4TVZZbTl2YldWeVlXNW5jR3hoZEdadmNtMHVibVYwTUlJQgpJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBcFRzZW96RTBzK2FsVzlTREpDREdyR0UyCmpXdVFTNis1NzBCbEhoVUJ5RzZZa0VRYWFkVFEwQUt0NGhFWUtUa1lSeldMbUhub2p2by9rWWFUK2hrZTNtRkwKS2tncVRHNkFDSnVLaStoUi84d2J2M3c3cTNOb0drc0lMYzA3RHBGeU0vejNzci9DakU4YmhjUnFMS0RJQzc4ZApRSDBwSXp3NSswLzNUTWllbWVUOWRLbERtZ1k5cEVtRGxpSHY1UkNFd0hPZjlUcXViR0dtdEMyNS9lT2JnTm9JCmxuOThTb2d2eXJRemZnTlhLVmdFVUVROHVqL3J5Tk5aQTRla2FLWS9oN2J5MjVjNlBVZW9uUlM1b3pVTGJ5VTMKaUFFUmRaTEgxVUxHdkgrRkNTY05CekRCcExheEZiWjltcC9iM3luVkIvOEkxeW5DVnRjRCtoNFBzNTlqYVFJRApBUUFCbzRJRGx6Q0NBNU13SHdZRFZSMGpCQmd3Rm9BVUtOTFA3Z21FZGQyMXNyVy9QTldneG5PSVhSOHdIUVlEClZSME9CQllFRkYrWk9tTzVLazkrcVRZMWJHanJ2enF3MFl0Qk1Gc0dBMVVkRVFSVU1GS0NGV0p2YjIxbGNtRnUKWjNCc1lYUm1iM0p0TG01bGRJSWJkRzl2YkhNdVltOXZiV1Z5WVc1bmNHeGhkR1p2Y20wdWJtVjBnaHh3ZFdKcwphV011WW05dmJXVnlZVzVuY0d4aGRHWnZjbTB1Ym1WME1Fb0dBMVVkSUFSRE1FRXdDd1lKWUlaSUFZYjliQUlCCk1ESUdCV2VCREFFQk1Da3dKd1lJS3dZQkJRVUhBZ0VXRzJoMGRIQTZMeTkzZDNjdVpHbG5hV05sY25RdVkyOXQKTDBOUVV6QU9CZ05WSFE4QkFmOEVCQU1DQmFBd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRgpCd01DTUhVR0ExVWRId1J1TUd3d05LQXlvRENHTG1oMGRIQTZMeTlqY213ekxtUnBaMmxqWlhKMExtTnZiUzlIClpXOVVjblZ6ZEVWV1VsTkJRMEZITWk1amNtd3dOS0F5b0RDR0xtaDBkSEE2THk5amNtdzBMbVJwWjJsalpYSjAKTG1OdmJTOUhaVzlVY25WemRFVldVbE5CUTBGSE1pNWpjbXd3Y3dZSUt3WUJCUVVIQVFFRVp6QmxNQ1FHQ0NzRwpBUVVGQnpBQmhoaG9kSFJ3T2k4dmIyTnpjQzVrYVdkcFkyVnlkQzVqYjIwd1BRWUlLd1lCQlFVSE1BS0dNV2gwCmRIQTZMeTlqWVdObGNuUnpMbVJwWjJsalpYSjBMbU52YlM5SFpXOVVjblZ6ZEVWV1VsTkJRMEZITWk1amNuUXcKREFZRFZSMFRBUUgvQkFJd0FEQ0NBWDBHQ2lzR0FRUUIxbmtDQkFJRWdnRnRCSUlCYVFGbkFIVUFEbGVVdlBPdQpxVDR6R3l5WkI3UDNrTitid2oxeE1pWGRJYWtsckdIRlRpRUFBQUdWWFkreTlBQUFCQU1BUmpCRUFpQjh3RjNVCmdrZUhEUHB0VmdLVlBWY0NZdG5JalBIb3B2WVd1UlFNTTdlUmx3SWdhSGdRZGRzUmQ2a09HemZwMGsyWVB2aXYKandNTEdJdElDVWFPeEF5ZjJsUUFkUUJrRWNSc3BCTHNwNGtjb2dJdUFMeXJUeWdIMUI0MUo2dnEvdFVEeVgzTgo4QUFBQVpWZGo3TW5BQUFFQXdCR01FUUNJRkVwUXJoSS9xQmRCbmxkQzJEYXN5bGo2U0huajNWa2dNQ1UvNGxnCmRXYlRBaUJzeDFRR0dnTlVDeCt2UTFPZzJCOFdTcldiWHhyZ00rTjg0RHRSZ0lJSjN3QjNBRW1jbTJuZUhYenMKL0RiZXpZZGtwcmhicndxSGdCblJWVkw3NmVzcDNmakRBQUFCbFYyUHN6a0FBQVFEQUVnd1JnSWhBUDZaWlBVcgpGdGpZVDFNMlE2eDdWd2VsNlFNYTN4eGlLN2doQy9uNFJXbmhBaUVBdFA0TjBhYXpPcGZoT2FkQ3hIa3RVb3ZZCkZWdzlINzFZZ0Q5S2dZR2hQNTh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUsrR3I4SU53TjVIblBBUFdxMncKdGs2TFd6aCtqdGFmWStxN3o3bmVldUdWWFl6SnRFVlNNZGhMNDgxY2h6WkQyMkVBK1RXdFdLQ0lSOXR6NkJucQp4M0dBV2NXTjNVS2dCVDJGN2NYak02eTYzc2ZDcWZvMy9FOEtjYU1RSTJiRjZDV01SUlRRZm1QTzVuUTlJQi9jClZvdjFUQ1c3ZmZ6YU9uM0xZUGpwRExBbXZ6N20xdWlBQjJIUUl0L2NEVFFlNHY1SE9rM0xZVkpmcEZrcW5jMkIKTkpscE92bms2cmdJVThaVTZiSHVReEdTaU04WWsrcEZsMTBDL1lTSCs2bDRyN2V4dTB5VGYvZ24xT2pmN3FiZQpFZHo5U3lNYzlhTitLeVg2Qktxa3Rza2ZWei9uZmdCalZIM2JyZGl6bXMrVVR0ajNGY09zeU5mYTQ2UThDUVltCld0QT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRlBEQ0NCQ1NnQXdJQkFnSVFEV0FTWXNpbmNocHVxd05oNVdHVmdEQU5CZ2txaGtpRzl3MEJBUXNGQURCaApNUXN3Q1FZRFZRUUdFd0pWVXpFVk1CTUdBMVVFQ2hNTVJHbG5hVU5sY25RZ1NXNWpNUmt3RndZRFZRUUxFeEIzCmQzY3VaR2xuYVdObGNuUXVZMjl0TVNBd0hnWURWUVFERXhkRWFXZHBRMlZ5ZENCSGJHOWlZV3dnVW05dmRDQkgKTWpBZUZ3MHlNREEzTURJeE1qUXlOVGRhRncwek1EQTNNREl4TWpReU5UZGFNRVF4Q3pBSkJnTlZCQVlUQWxWVApNUlV3RXdZRFZRUUtFd3hFYVdkcFEyVnlkQ0JKYm1NeEhqQWNCZ05WQkFNVEZVZGxiMVJ5ZFhOMElFVldJRkpUClFTQkRRU0JITWpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTkRTdkZNTUdJT0kKRDJOK3JweWFHVFBmeUl0cDNhdEN5aW1SSkNQdEFha1U5ODRFQjE5WnVncmI4MnVpMGl5MHpMS01Eck91TitLdQpINmpGNEY0WkNvSGpON3RGZE10U3NDVUFicnBGVk8vNUJMWStWVElnN1lVTjVMd1JIVWIyUVZTR3dLeUllWVMrClNxUFY4bXpUTWtHOUduV2pHMUlRVDBGMStYdTcrdUFHUkZWbklkWUNTQmdsN2lHNHFPV1pqY1BLblcrM09KUk8KZFp0d0dFMzlFN1dvYXNvVzhOdnB1NUZGcDJXSXN2WTZCLzB3aHIzdyt4S2VCWWIyV05LSTFaWHZrNHkrQW1VYQpCZFJUWTBIUEJaNCs2SXBjcTJSbCtRTFFYUXVHWEg5NVl1allOWXBiblY3QVNVNS9kVm1xVlBZMExIbnAyc05LCklONjUvbitEYmNzQ0F3RUFBYU9DQWdzd2dnSUhNQjBHQTFVZERnUVdCQlFvMHMvdUNZUjEzYld5dGI4ODFhREcKYzRoZEh6QWZCZ05WSFNNRUdEQVdnQlJPSWxRZ0dKWG00MjdtRC9yNnVSTHRCaGVQT1RBT0JnTlZIUThCQWY4RQpCQU1DQVlZd0hRWURWUjBsQkJZd0ZBWUlLd1lCQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQklHQTFVZEV3RUIvd1FJCk1BWUJBZjhDQVFBd05BWUlLd1lCQlFVSEFRRUVLREFtTUNRR0NDc0dBUVVGQnpBQmhoaG9kSFJ3T2k4dmIyTnoKY0M1a2FXZHBZMlZ5ZEM1amIyMHdld1lEVlIwZkJIUXdjakEzb0RXZ000WXhhSFIwY0RvdkwyTnliRE11WkdsbgphV05sY25RdVkyOXRMMFJwWjJsRFpYSjBSMnh2WW1Gc1VtOXZkRWN5TG1OeWJEQTNvRFdnTTRZeGFIUjBjRG92CkwyTnliRFF1WkdsbmFXTmxjblF1WTI5dEwwUnBaMmxEWlhKMFIyeHZZbUZzVW05dmRFY3lMbU55YkRDQnpnWUQKVlIwZ0JJSEdNSUhETUlIQUJnUlZIU0FBTUlHM01DZ0dDQ3NHQVFVRkJ3SUJGaHhvZEhSd2N6b3ZMM2QzZHk1awphV2RwWTJWeWRDNWpiMjB2UTFCVE1JR0tCZ2dyQmdFRkJRY0NBakIrREh4QmJua2dkWE5sSUc5bUlIUm9hWE1nClEyVnlkR2xtYVdOaGRHVWdZMjl1YzNScGRIVjBaWE1nWVdOalpYQjBZVzVqWlNCdlppQjBhR1VnVW1Wc2VXbHUKWnlCUVlYSjBlU0JCWjNKbFpXMWxiblFnYkc5allYUmxaQ0JoZENCb2RIUndjem92TDNkM2R5NWthV2RwWTJWeQpkQzVqYjIwdmNuQmhMWFZoTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCVmJRczhLRDZxUm5PZi9kdE9ITkF5Cmllb1JjQTFaazNsR01Md3FOZnVMcFRiOWdEUUZwdnhHTi8zWDdpMG1BRXRSaE4vcjlmRHY4b2lWTG42Z2ZwbTAKVVVONDd2RkpDemY1ZHFrVi9ON0xrTVRxbGhEQTBWZS9HQkozQTJFNXlGVDdUZ0FHTjR3SjljQ1pyS2JxS0hWVQpSYXR3SitUNThqbWhidnRFTTd0MnVjQjd1K0RtdTRLb09URXg4TFI4K3FuOE95TGgxVkxxNzV2ekRUc25oVE41CjNBZ1BkTVZGazZGOHNqVDJQMnhidkFiMGtBbHlBdGxkQXRwR3ZCelhoYWNtUnM3clRxei9vVER3WVpMa3JtK3EKRWx0ZG1Hd1VPV3ZGUGp3dWNINnRTK2dRZ2lVWWlOSnFpanpJMWpyOFRaMDFWR09TVFc3clJVS2drTjVXSnFEQQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCi0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlEampDQ0FuYWdBd0lCQWdJUUF6cng1cWNScWFDN0tHU3hIUW42NVRBTkJna3Foa2lHOXcwQkFRc0ZBREJoCk1Rc3dDUVlEVlFRR0V3SlZVekVWTUJNR0ExVUVDaE1NUkdsbmFVTmxjblFnU1c1ak1Sa3dGd1lEVlFRTEV4QjMKZDNjdVpHbG5hV05sY25RdVkyOXRNU0F3SGdZRFZRUURFeGRFYVdkcFEyVnlkQ0JIYkc5aVlXd2dVbTl2ZENCSApNakFlRncweE16QTRNREV4TWpBd01EQmFGdzB6T0RBeE1UVXhNakF3TURCYU1HRXhDekFKQmdOVkJBWVRBbFZUCk1SVXdFd1lEVlFRS0V3eEVhV2RwUTJWeWRDQkpibU14R1RBWEJnTlZCQXNURUhkM2R5NWthV2RwWTJWeWRDNWoKYjIweElEQWVCZ05WQkFNVEYwUnBaMmxEWlhKMElFZHNiMkpoYkNCU2IyOTBJRWN5TUlJQklqQU5CZ2txaGtpRwo5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBdXpmTk5OeDdhOG15YUpDdFNuWC9Scm9oQ2dpTjlSbFV5ZnVJCjIvT3U4anFKa1R4NjVxc0dHbXZQckMzb1hna2tSTHBpbW43V282aCs0RlIxSUFXc1VMZWNZeHBzTU56YUh4bXgKMXg3ZS9kZmd5NVNETjY3c0gwTk8zWHNzMHIwdXBTL2txYml0T3RTWnBMWWw2WnRyQUdDU1lQOVBJVWtZOTJlUQpxMkVHbkkveXV1bTA2Wkl5YTdYelYraGRHODJNSGF1VkJKVko4elV0bHVOSmJkMTM0L3RKUzdTc1ZRZXBqNVd6CnRDTzdURzFGOFBhcHNwVXd0UDFNVll3blNsY1VmSUtkelhPUzB4WktCZ3lNVU5HUEhnbStGNkhtSWNyOWcrVVEKdklPbENzUm5LUFp6RkJROVJuYkRoeFNKSVRSTnJ3OUZES1pKb2JxN25NV3hNNE1waFFJREFRQUJvMEl3UURBUApCZ05WSFJNQkFmOEVCVEFEQVFIL01BNEdBMVVkRHdFQi93UUVBd0lCaGpBZEJnTlZIUTRFRmdRVVRpSlVJQmlWCjV1TnU1Zy82K3JrUzdRWVhqemt3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUdCbktKUnZEa2hqNnpIZDZtY1kKMVlsOVBNV0xTbi9wdnRzckY5K3dYM04zS2pJVE9ZRm5Rb1FqOGtWbk5leUl2L2lQc0dFTU5LU3VJRXlFeHR2NApOZUYyMmQrbVFydkhSQWlHZnpaMEpGcmFiQTBVV1RXOThrbmR0aC9Kc3cxSEtqMlpMN3RjdTdYVUlPR1pYMU5HCkZkdG9tL0R6TU5VK01lS05oSjdqaXRyYWxqNDFFNlZmOFBsd1VIQkhRUkZYR1U3QWo2NEd4SlVURnk4YkpaOTEKOHJHT21hRnZFN0ZCY2Y2SUtzaFBFQ0JWMS9NVVJlWGdSUFRxaDVVeWt3NytVMGI2TEozL2l5SzVTOWtKUmFUZQpwTGlhV04wYmZWS2ZqbGxEaUlHa25pYlZiNjNkRGNZM2ZlMERraHZsZDE5MjdqeU54RjFXVzZMWlptNnpOVGZsCk1yWT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRGpqQ0NBbmFnQXdJQkFnSVFBenJ4NXFjUnFhQzdLR1N4SFFuNjVUQU5CZ2txaGtpRzl3MEJBUXNGQURCaApNUXN3Q1FZRFZRUUdFd0pWVXpFVk1CTUdBMVVFQ2hNTVJHbG5hVU5sY25RZ1NXNWpNUmt3RndZRFZRUUxFeEIzCmQzY3VaR2xuYVdObGNuUXVZMjl0TVNBd0hnWURWUVFERXhkRWFXZHBRMlZ5ZENCSGJHOWlZV3dnVW05dmRDQkgKTWpBZUZ3MHhNekE0TURFeE1qQXdNREJhRncwek9EQXhNVFV4TWpBd01EQmFNR0V4Q3pBSkJnTlZCQVlUQWxWVApNUlV3RXdZRFZRUUtFd3hFYVdkcFEyVnlkQ0JKYm1NeEdUQVhCZ05WQkFzVEVIZDNkeTVrYVdkcFkyVnlkQzVqCmIyMHhJREFlQmdOVkJBTVRGMFJwWjJsRFpYSjBJRWRzYjJKaGJDQlNiMjkwSUVjeU1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXV6Zk5OTng3YThteWFKQ3RTblgvUnJvaENnaU45UmxVeWZ1SQoyL091OGpxSmtUeDY1cXNHR212UHJDM29YZ2trUkxwaW1uN1dvNmgrNEZSMUlBV3NVTGVjWXhwc01OemFIeG14CjF4N2UvZGZneTVTRE42N3NIME5PM1hzczByMHVwUy9rcWJpdE90U1pwTFlsNlp0ckFHQ1NZUDlQSVVrWTkyZVEKcTJFR25JL3l1dW0wNlpJeWE3WHpWK2hkRzgyTUhhdVZCSlZKOHpVdGx1TkpiZDEzNC90SlM3U3NWUWVwajVXegp0Q083VEcxRjhQYXBzcFV3dFAxTVZZd25TbGNVZklLZHpYT1MweFpLQmd5TVVOR1BIZ20rRjZIbUljcjlnK1VRCnZJT2xDc1JuS1BaekZCUTlSbmJEaHhTSklUUk5ydzlGREtaSm9icTduTVd4TTRNcGhRSURBUUFCbzBJd1FEQVAKQmdOVkhSTUJBZjhFQlRBREFRSC9NQTRHQTFVZER3RUIvd1FFQXdJQmhqQWRCZ05WSFE0RUZnUVVUaUpVSUJpVgo1dU51NWcvNitya1M3UVlYanprd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFHQm5LSlJ2RGtoajZ6SGQ2bWNZCjFZbDlQTVdMU24vcHZ0c3JGOSt3WDNOM0tqSVRPWUZuUW9RajhrVm5OZXlJdi9pUHNHRU1OS1N1SUV5RXh0djQKTmVGMjJkK21RcnZIUkFpR2Z6WjBKRnJhYkEwVVdUVzk4a25kdGgvSnN3MUhLajJaTDd0Y3U3WFVJT0daWDFORwpGZHRvbS9Eek1OVStNZUtOaEo3aml0cmFsajQxRTZWZjhQbHdVSEJIUVJGWEdVN0FqNjRHeEpVVEZ5OGJKWjkxCjhyR09tYUZ2RTdGQmNmNklLc2hQRUNCVjEvTVVSZVhnUlBUcWg1VXlrdzcrVTBiNkxKMy9peUs1UzlrSlJhVGUKcExpYVdOMGJmVktmamxsRGlJR2tuaWJWYjYzZERjWTNmZTBEa2h2bGQxOTI3anlOeEYxV1c2TFpabTZ6TlRmbApNclk9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0KLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZQRENDQkNTZ0F3SUJBZ0lRRFdBU1lzaW5jaHB1cXdOaDVXR1ZnREFOQmdrcWhraUc5dzBCQVFzRkFEQmgKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVJrd0Z3WURWUVFMRXhCMwpkM2N1WkdsbmFXTmxjblF1WTI5dE1TQXdIZ1lEVlFRREV4ZEVhV2RwUTJWeWRDQkhiRzlpWVd3Z1VtOXZkQ0JICk1qQWVGdzB5TURBM01ESXhNalF5TlRkYUZ3MHpNREEzTURJeE1qUXlOVGRhTUVReEN6QUpCZ05WQkFZVEFsVlQKTVJVd0V3WURWUVFLRXd4RWFXZHBRMlZ5ZENCSmJtTXhIakFjQmdOVkJBTVRGVWRsYjFSeWRYTjBJRVZXSUZKVApRU0JEUVNCSE1qQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0NnZ0VCQU5EU3ZGTU1HSU9JCkQyTitycHlhR1RQZnlJdHAzYXRDeWltUkpDUHRBYWtVOTg0RUIxOVp1Z3JiODJ1aTBpeTB6TEtNRHJPdU4rS3UKSDZqRjRGNFpDb0hqTjd0RmRNdFNzQ1VBYnJwRlZPLzVCTFkrVlRJZzdZVU41THdSSFViMlFWU0d3S3lJZVlTKwpTcVBWOG16VE1rRzlHbldqRzFJUVQwRjErWHU3K3VBR1JGVm5JZFlDU0JnbDdpRzRxT1daamNQS25XKzNPSlJPCmRadHdHRTM5RTdXb2Fzb1c4TnZwdTVGRnAyV0lzdlk2Qi8wd2hyM3creEtlQlliMldOS0kxWlh2azR5K0FtVWEKQmRSVFkwSFBCWjQrNklwY3EyUmwrUUxRWFF1R1hIOTVZdWpZTllwYm5WN0FTVTUvZFZtcVZQWTBMSG5wMnNOSwpJTjY1L24rRGJjc0NBd0VBQWFPQ0Fnc3dnZ0lITUIwR0ExVWREZ1FXQkJRbzBzL3VDWVIxM2JXeXRiODgxYURHCmM0aGRIekFmQmdOVkhTTUVHREFXZ0JST0lsUWdHSlhtNDI3bUQvcjZ1Ukx0QmhlUE9UQU9CZ05WSFE4QkFmOEUKQkFNQ0FZWXdIUVlEVlIwbEJCWXdGQVlJS3dZQkJRVUhBd0VHQ0NzR0FRVUZCd01DTUJJR0ExVWRFd0VCL3dRSQpNQVlCQWY4Q0FRQXdOQVlJS3dZQkJRVUhBUUVFS0RBbU1DUUdDQ3NHQVFVRkJ6QUJoaGhvZEhSd09pOHZiMk56CmNDNWthV2RwWTJWeWRDNWpiMjB3ZXdZRFZSMGZCSFF3Y2pBM29EV2dNNFl4YUhSMGNEb3ZMMk55YkRNdVpHbG4KYVdObGNuUXVZMjl0TDBScFoybERaWEowUjJ4dlltRnNVbTl2ZEVjeUxtTnliREEzb0RXZ000WXhhSFIwY0RvdgpMMk55YkRRdVpHbG5hV05sY25RdVkyOXRMMFJwWjJsRFpYSjBSMnh2WW1Gc1VtOXZkRWN5TG1OeWJEQ0J6Z1lEClZSMGdCSUhHTUlIRE1JSEFCZ1JWSFNBQU1JRzNNQ2dHQ0NzR0FRVUZCd0lCRmh4b2RIUndjem92TDNkM2R5NWsKYVdkcFkyVnlkQzVqYjIwdlExQlRNSUdLQmdnckJnRUZCUWNDQWpCK0RIeEJibmtnZFhObElHOW1JSFJvYVhNZwpRMlZ5ZEdsbWFXTmhkR1VnWTI5dWMzUnBkSFYwWlhNZ1lXTmpaWEIwWVc1alpTQnZaaUIwYUdVZ1VtVnNlV2x1Clp5QlFZWEowZVNCQlozSmxaVzFsYm5RZ2JHOWpZWFJsWkNCaGRDQm9kSFJ3Y3pvdkwzZDNkeTVrYVdkcFkyVnkKZEM1amIyMHZjbkJoTFhWaE1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlZiUXM4S0Q2cVJuT2YvZHRPSE5BeQppZW9SY0ExWmszbEdNTHdxTmZ1THBUYjlnRFFGcHZ4R04vM1g3aTBtQUV0UmhOL3I5ZkR2OG9pVkxuNmdmcG0wClVVTjQ3dkZKQ3pmNWRxa1YvTjdMa01UcWxoREEwVmUvR0JKM0EyRTV5RlQ3VGdBR040d0o5Y0NackticUtIVlUKUmF0d0orVDU4am1oYnZ0RU03dDJ1Y0I3dStEbXU0S29PVEV4OExSOCtxbjhPeUxoMVZMcTc1dnpEVHNuaFRONQozQWdQZE1WRms2RjhzalQyUDJ4YnZBYjBrQWx5QXRsZEF0cEd2QnpYaGFjbVJzN3JUcXovb1REd1laTGtybStxCkVsdGRtR3dVT1d2RlBqd3VjSDZ0UytnUWdpVVlpTkpxaWp6STFqcjhUWjAxVkdPU1RXN3JSVUtna041V0pxREEKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  