{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "rbac" -}}
{{- $values := .Values -}}
{{- $context := . -}}
{{- if $values.workers.security.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "component" "worker" ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "bmrg.name" (dict "context" $context "component" "worker" ) }}
subjects:
- kind: ServiceAccount
  name: {{ include "bmrg.name" (dict "context" $context "component" "worker" ) }}
  namespace: {{ $.Release.Namespace }}
{{- end }}