{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "rbac" -}}
{{- $values := .Values -}}
{{- $context := . -}}
{{- if $values.tasks.security.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "component" "agent" ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
{{- end }}