{{- $platform := "bmrg" -}}
{{- $product := "flow" -}}
{{- $tier := "secrets" -}}
{{-$values := $values -}}
{{- $context := $context -}}
# Start Generate Secret
# Solution by https://github.com/helm/charts/issues/5167
{{- $otc := (randAlphaNum 45) | b64enc | quote -}}
{{- $encryptSecret := (randAlphaNum 16) | b64enc | quote -}}
{{- $encryptSalt := (randAlphaNum 16) | b64enc | quote -}}
{{- $secret := (lookup "v1" "Secret" .Release.Namespace "bmrg-flow-secrets") -}}
{{- if $secret -}}
{{- $otc = index $secret.data "FLOW_OTC" -}}
{{- $encryptSecret = index $secret.data "FLOW_ENCRYPT_SECRET" -}}
{{- $encryptSalt = index $secret.data "FLOW_ENCRYPT_SALT" -}}
{{- end -}}
# End Generate Secret
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bmrg.name" (dict "context" $context "tier" $tier ) }}
  labels:
    {{- include "bmrg.labels.chart" (dict "context" $context "tier" $tier ) | nindent 4 }}
  annotations:
    helm.sh/hook-weight: "-1"
type: Opaque
data:
  {{- if not $.Values.database.mongodb.secretName }}
  MONGODB_PASSWORD: {{ $.Values.database.mongodb.password | b64enc }}
  {{- end }}
  FLOW_OTC: {{ $otc }}
  FLOW_ENCRYPT_SECRET: {{ $encryptSecret }}
  FLOW_ENCRYPT_SALT: {{ $encryptSalt }}